import { useEffect, useRef, useState } from 'react'
import { AnimatePresence, motion, useReducedMotion } from 'framer-motion'
import { NavLink, useLocation } from 'react-router-dom'
import { navigation } from '../../data/navigation'
import { Button } from '../ui/Button'
import { Container } from '../ui/Container'
import { BrandMark } from './BrandMark'

const navClass = ({ isActive }: { isActive: boolean }) => `relative flex min-h-11 items-center text-sm font-semibold transition-colors ${isActive ? 'text-timber after:absolute after:bottom-0 after:h-0.5 after:w-full after:bg-timber' : 'text-charcoal hover:text-timber'}`
export function Navbar() {
 const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false); const triggerRef = useRef<HTMLButtonElement>(null); const panelRef = useRef<HTMLDivElement>(null); const location = useLocation(); const reduced = useReducedMotion()
 useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 12); onScroll(); window.addEventListener('scroll', onScroll, { passive: true }); return () => window.removeEventListener('scroll', onScroll) }, [])
 useEffect(() => { setOpen(false) }, [location.pathname])
 useEffect(() => { if (!open) return; const original = document.body.style.overflow; document.body.style.overflow = 'hidden'; const onKey = (event: KeyboardEvent) => { if (event.key === 'Escape') setOpen(false); if (event.key === 'Tab' && panelRef.current) { const items = panelRef.current.querySelectorAll<HTMLElement>('a,button:not([disabled])'); const first = items[0], last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus() } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus() } } }; document.addEventListener('keydown', onKey); panelRef.current?.querySelector<HTMLElement>('a')?.focus(); return () => { document.body.style.overflow = original; document.removeEventListener('keydown', onKey); triggerRef.current?.focus() } }, [open])
 const close = () => setOpen(false)
 return <header className={`sticky top-0 z-50 border-b transition-colors duration-200 ${scrolled ? 'border-warm-grey bg-canvas/95 shadow-sm backdrop-blur-sm' : 'border-transparent bg-canvas'}`}><Container><div className={`flex items-center justify-between transition-[height] duration-200 ${scrolled ? 'h-16' : 'h-20'}`}><BrandMark /><nav className="hidden items-center gap-7 lg:flex" aria-label="Primary navigation">{navigation.map(item => <NavLink key={item.to} to={item.to} className={navClass}>{item.label}</NavLink>)}<Button to="/contact" className="ml-2">Get a Free Quote</Button></nav><button ref={triggerRef} type="button" className="inline-flex min-h-12 min-w-12 items-center justify-center border border-warm-grey text-charcoal lg:hidden" aria-label={open ? 'Close navigation menu' : 'Open navigation menu'} aria-expanded={open} aria-controls="mobile-navigation" onClick={() => setOpen(value => !value)}><span className="sr-only">Menu</span><span aria-hidden="true" className="text-xl leading-none">{open ? '×' : '☰'}</span></button></div></Container><AnimatePresence>{open && <motion.div id="mobile-navigation" ref={panelRef} className="fixed inset-x-0 bottom-0 top-0 z-50 flex flex-col bg-deep-charcoal px-5 pb-8 pt-5 text-white sm:px-8" initial={{ opacity: 0, x: reduced ? 0 : '100%' }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: reduced ? 0 : '100%' }} transition={{ duration: reduced ? 0 : 0.25 }} role="dialog" aria-modal="true" aria-label="Mobile navigation"><div className="flex items-center justify-between"><BrandMark inverted onNavigate={close} /><button type="button" className="inline-flex min-h-12 min-w-12 items-center justify-center border border-white/30" onClick={close} aria-label="Close navigation menu"><span aria-hidden="true" className="text-2xl">×</span></button></div><nav className="mt-auto flex flex-col border-t border-white/15" aria-label="Mobile primary navigation">{navigation.map(item => <NavLink key={item.to} to={item.to} onClick={close} className={({ isActive }) => `flex min-h-16 items-center border-b border-white/15 text-2xl font-semibold ${isActive ? 'text-bronze' : 'text-white'}`}>{item.label}</NavLink>)}</nav><Button to="/contact" onClick={close} className="mt-8">Get a Free Quote</Button></motion.div>}</AnimatePresence></header>
}
