import { motion, useReducedMotion } from 'framer-motion'
import { Button } from '../ui/Button'
import { Container } from '../ui/Container'
import { imageReveal, revealUp } from '../../animations/variants'
import { ProjectPlaceholder } from './ProjectPlaceholder'
export function Hero() {
 const reduced = useReducedMotion()
 return <section className="overflow-hidden bg-deep-charcoal text-white"><Container><div className="grid min-h-[calc(100svh-5rem)] items-center gap-10 py-12 lg:grid-cols-12 lg:gap-0 lg:py-16"><div className="relative z-10 lg:col-span-7 lg:pr-14"><motion.p variants={revealUp(reduced)} initial="hidden" animate="visible" className="text-xs font-bold uppercase tracking-[0.22em] text-bronze">Shades and Decking NZ</motion.p><motion.h1 variants={revealUp(reduced, 0.08)} initial="hidden" animate="visible" className="mt-6 max-w-3xl text-5xl font-semibold leading-[0.92] tracking-[-0.065em] sm:text-6xl md:text-7xl lg:text-8xl">CREATE.<br />RELAX.<br /><span className="text-bronze">ENJOY.</span></motion.h1><motion.p variants={revealUp(reduced, 0.16)} initial="hidden" animate="visible" className="mt-7 max-w-lg text-lg leading-8 text-white/75 sm:text-xl">Premium outdoor spaces built for New Zealand living.</motion.p><motion.div variants={revealUp(reduced, 0.24)} initial="hidden" animate="visible" className="mt-9 flex flex-col gap-3 sm:flex-row"><Button to="/contact">Get a Free Consultation &amp; Quote</Button><Button to="/services" variant="outline" className="border-white/70 text-white hover:bg-white hover:text-charcoal">Explore Our Services</Button></motion.div></div><motion.div variants={imageReveal(reduced)} initial="hidden" animate="visible" className="relative lg:col-span-5 lg:col-start-8"><ProjectPlaceholder priority label="Hero project photography placeholder" className="aspect-[5/6] min-h-[300px] sm:aspect-[16/10] lg:aspect-[4/5]" /><div className="absolute -bottom-4 -left-4 hidden h-20 w-20 border-b border-l border-bronze sm:block" /></motion.div></div></Container></section>
}
