import { BrowserRouter, Route, Routes } from 'react-router-dom'
import { AppLayout } from './components/layout/AppLayout'
import { Seo } from './components/ui/Seo'
import { StructuredData } from './components/ui/StructuredData'
import { About } from './pages/About'
import { Contact } from './pages/Contact'
import { Home } from './pages/Home'
import { Services } from './pages/Services'
import { NotFound } from './pages/NotFound'
export function App() { return <BrowserRouter><Seo /><StructuredData /><AppLayout><Routes><Route path="/" element={<Home />} /><Route path="/about" element={<About />} /><Route path="/services" element={<Services />} /><Route path="/contact" element={<Contact />} /><Route path="*" element={<NotFound />} /></Routes></AppLayout></BrowserRouter> }
